spring.application.name=jwt-authenticator
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/base-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:base}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:base}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

app.jwt.secret=${APP_JWT_SECRET:YrRZyvDR72HEn+z+EmjcYdBRY1Nw3uDncT6lLv8HEgkj90p2m8uWTcgXMWPydoMH9VRIj1E29QP4LhgFF59dCw==}
app.jwt.expiration=${APP_JWT_EXP:3600000}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

app.security.refresh.remember-days=30
app.security.refresh.rotate=true
app.security.refresh.days=90
app.security.refresh.max-active-sessions=5

app.security.refresh.cookie-name:refresh_token
app.security.refresh.cookie-path:/api/auth
app.security.refresh.secure:false
app.security.refresh.same-site:Lax

# Actuator endpoints
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true

# Métriques détaillées
management.metrics.enable.jvm=true
management.metrics.enable.http=true
management.metrics.enable.jdbc=true
management.metrics.export.prometheus.enabled=true

# Logs Hibernate (pour voir les requêtes)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=300000
spring.data.redis.repositories.enabled=false